const conjunctions = ["but", "and", "then", "for", "if", "when", "after", "before", "because", "so", "or", "also"];
const adjectives = ["big", "hot", "red", "wet", "new", "old", "fat", "bad", "mad", "sad", "fun", "bald", "hard", "soft", "green", "dry", "purple", "orange", "black", "white", "small", "raw", "little", "thin", "dim", "fit", "tall", "wet", "zip", "cool", "warm", "long", "hard", "soft", "fast", "slow", "happy", "rich", "poor", "blue", "wise", "short", "yellow", "old", "young"];
const nouns = ["cat", "dog", "pig", "man", "ant", "pup", "rat", "bat", "hat", "fox", "den", "hen", "cap", "mat", "pen", "car", "box", "hen", "sun", "pot", "jar", "log", "bed", "pan", "mug", "bug", "lip", "lap", "lad", "bag", "bed", "pan", "ball", "hut", "mom", "pod", "dad", "girl", "boy", "moon", "star", "bird", "fish", "milk", "food", "zip", "tree", "seed", "leaf", "ship", "ring", "bell", "boat", "root", "door", "chair", "table", "key", "horse", "monkey", "chicken", "house"];
const verbs = ["run", "sit", "hop", "dig", "fix", "win", "cut", "hit", "nod", "tap", "tug", "saw", "mix", "dig", "pat", "pop", "pet", "ran", "bite", "put", "drop", "feed", "jump", "fall", "drink", "sing", "cry", "swim", "see", "fly", "lie", "buy", "pay", "say", "eat", "sip", "rip", "read", "ride", "write", "open", "shut", "sing", "fly", "ring", "talk", "walk", "take", "roll" , "crawl", "dance", "laugh"];
const adverbs = ["now", "yet", "too", "low", "high", "near", "far", "well", "fast", "hard", "then", "here", "soon", "late", "very", "just", "also", "early", "there", "quite", "often", "never", "seldom", "almost", "always"];
const spatialPrepositions = ["up", "down", "on", "under", "left", "right", "beside", "behind", "where"];
const questionWords = ["when", "how"];


export { conjunctions, adjectives, nouns, verbs, adverbs, spatialPrepositions, questionWords };